spring:
  application:
    name: lionproject2-backend

  datasource:
    url: jdbc:mysql://localhost:3306/lionproject2
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    filter:
      order: -100

jwt:
  secret: m8N2p9Vb+e2Xc0s9R7a+9L1zY9A5KqC2mZ0Y+ZxHq+0=
  access-exp-ms: 1800000     # 30분
  refresh-exp-ms: 604800000  # 7일

app:
  cookie:
    refresh-name: "refreshToken"
    refresh-path: "/"
    refresh-same-site: "Lax"
    refresh-secure: false